FROM node:alpine AS build
RUN apk update
RUN apk add --no-cache git

WORKDIR /app
ENV PNPM_VERSION=6.30.0
ARG VITE_PUBLIC_GRAPHQL_API_URL_HTTP
ENV VITE_PUBLIC_GRAPHQL_API_URL_HTTP $VITE_PUBLIC_GRAPHQL_API_URL_HTTP
ARG VITE_PUBLIC_GRAPHQL_API_URL_WS
ENV VITE_PUBLIC_GRAPHQL_API_URL_WS $VITE_PUBLIC_GRAPHQL_API_URL_WS
ARG VITE_PUBLIC_FILES_BASE_URL
ENV VITE_PUBLIC_FILES_BASE_URL $VITE_PUBLIC_FILES_BASE_URL
ARG VITE_PUBLIC_I18N_BASE_URL
ENV VITE_PUBLIC_I18N_BASE_URL $VITE_PUBLIC_I18N_BASE_URL
ARG VITE_PUBLIC_STOREFRONT_HOME_URL
ENV VITE_PUBLIC_STOREFRONT_HOME_URL $VITE_PUBLIC_STOREFRONT_HOME_URL
ARG VITE_ROOT_URL
ENV VITE_ROOT_URL $VITE_ROOT_URL
ARG VITE_PUBLIC_REST_API_URL
ENV VITE_PUBLIC_REST_API_URL $VITE_PUBLIC_REST_API_URL

RUN npm i -g pnpm@${PNPM_VERSION}
COPY pnpm-lock.yaml ./
RUN pnpm fetch
RUN ls -a

COPY . .
RUN pnpm install --frozen-lock

RUN pnpm run build:admin

FROM nginx:stable

EXPOSE 80
WORKDIR /app

COPY --from=build /app/apps/admin/dist /usr/share/nginx/html

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]
