name: Publish Docker Image
on:
  push:
    branches:
      - 'trunk'
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19.0.2
        extra_plugins: |
          @semantic-release/changelog
          @codedependant/semantic-release-docker
          @semantic-release/commit-analyzer
          @semantic-release/git
          @semantic-release/release-notes-generator
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_REGISTRY_USER }}

